### PR TITLE
Add minimal footer

### PR DESCRIPTION
**Pull request by missx**
Add isMinimal prop to footer and display minimal footer. This footer is used in the welcome page variation of Masterclass.

## Risks
None

## Changes
image

### CODE REVIEW

**Comment by bernabe9** [comment]
Can you update the snapshots for this story?

Just run `yarn test`

**Comment by missx** [comment]
@bernabe9 Done!

**Comment by bernabe9** [comment]
@missx weird, it's duplicating the snapshots for all the stories.

Can you try this:
- undo your last commit
- rebase `master`
- run `yarn test -u`

That should change only the Footer snapshot

**Comment by missx** [comment]
@bernabe9 You mean develop?

**Comment by bernabe9** [comment]
ups, yes `develop` branch

**Comment by missx** [comment]
@bernabe9 I pushed the new changes after rebasing, but it still updated all of them.

**Comment by bernabe9** [comment]
@missx great! now it makes sense. Yes, the others snapshots were updated(but only text changes)

**Comment by bernabe9** [comment]
we should add the command `yarn test -u` as a precommit command to always keep tests updated.

**Pull request merged**
